version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore AWSDevOps.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output AWSDevOps.csproj
artifacts:
  files:
    - CodeBuild-AWSDevOps/build_output/**/*
    - scripts/**/*
    - appspec.yml
